version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo check if AWS ClI installed...
      - aws --version
      - echo check if Python installed...
      - python --version
      - echo check if PIP python package manager installed...
      - pip3 --version
      - echo Installing CFN-LINT..
      - pip3 install cfn-lint
      - echo check if CFN-LINT installed...
      - cfn-lint --version

  build:
    commands:
      - echo Validating the cnf template
      - cfn-lint 4-stage-pipeline.yaml
      - echo cfn template Build started on 'date'
      - aws cloudformation package --template-file 4-stage-pipeline.yaml --s3-bucket hera-codepipeline-source-bucket --output-template-file OutputTemplate.yaml

  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - OutputTemplate.yaml
    - 4-stage-pipeline.yaml